import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { css } from '../../styled-system/css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const className = css({
    borderColor: {
      base: 'gray.800',
      _focusWithin: 'purple.600',
      // @ts-ignore
      '&:has([aria-invalid])': 'red.7',
    }
  })

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
